spec:
  template:
    spec:
      containers:
      - name: app
        image: docker.io/library/python:3.12-alpine
        resources:
          limits:
            memory: "512Mi"
          requests:
            memory: "256Mi"
